Exiv2: Exiv2::Internal::Nikon3MnHeader Class Reference
Exiv2::Internal::Nikon3MnHeader Class Reference
Header of a Nikon 3 Makernote.
#include <makernote_int.hpp>
Public Member Functions
Creators
Nikon3MnHeader ()
Default constructor.
~Nikon3MnHeader () override=default
Virtual destructor.
Manipulators
bool read (const byte *pData, size_t size, ByteOrder byteOrder) override
Read the header from a data buffer, return true if ok.
void setByteOrder (ByteOrder byteOrder) override
Set the byte order for the makernote.
Public Member Functions inherited from Exiv2::Internal::MnHeader
virtual ~MnHeader ()=default
Virtual destructor.
Accessors
size_t size () const override
Return the size of the header (in bytes).
size_t write (IoWrapper &ioWrapper, ByteOrder byteOrder) const override
Write the header to a data buffer, return the number of bytes written.
size_t ifdOffset () const override
Return the offset to the start of the Makernote IFD from the start of the Makernote (= the start of the header).
ByteOrder byteOrder () const override
Return the byte order for the makernote. If the return value is invalidByteOrder, this means that the byte order of the the image should be used for the makernote.
uint32_t baseOffset (uint32_t mnOffset) const override
Return the base offset for the makernote IFD entries relative to the start of the TIFF header. mnOffset is the offset to the makernote from the start of the TIFF header.
static size_t sizeOfSignature ()
Return the size of the makernote header signature.
Detailed Description
Header of a Nikon 3 Makernote.
Member Function Documentation
write()
size_t Exiv2::Internal::Nikon3MnHeader::write (IoWrapper & ioWrapper, ByteOrder byteOrder) const override virtual
Write the header to a data buffer, return the number of bytes written.
Implements Exiv2::Internal::MnHeader.
References byteOrder(), Exiv2::DataBuf::c_data(), Exiv2::Internal::TiffHeaderBase::write(), and Exiv2::Internal::IoWrapper::write().
The documentation for this class was generated from the following files:
makernote_int.hpp
makernote_int.cpp