Exiv2: Exiv2::XmpArrayValue Class Reference
Exiv2::XmpArrayValue Class Reference
Value type for simple arrays. Each item in the array is a simple value, without qualifiers. The array may be an ordered (seq), unordered (bag) or alternative array (alt). The array items must not contain qualifiers. For language alternatives use LangAltValue.
#include <value.hpp>
Public Types
using UniquePtr = std::unique_ptr< XmpArrayValue >
Shortcut for a XmpArrayValue auto pointer.
Public Types inherited from Exiv2::XmpValue
enum XmpArrayType { xaNone , xaAlt , xaBag , xaSeq }
XMP array types.
enum XmpStruct { xsNone , xsStruct }
XMP structure indicator.
using UniquePtr = std::unique_ptr< XmpValue >
Shortcut for a XmpValue auto pointer.
Public Types inherited from Exiv2::Value
using UniquePtr = std::unique_ptr< Value >
Shortcut for a Value auto pointer.
Public Member Functions
Creators
XmpArrayValue (TypeId typeId=xmpBag)
Constructor. typeId can be one of xmpBag, xmpSeq or xmpAlt.
Manipulators
int read (const std::string &buf) override
Read a simple property value from buf and append it to the value.
int read (const byte *buf, size_t len, ByteOrder byteOrder=invalidByteOrder) override
int read (const std::string &buf) override=0
Public Member Functions inherited from Exiv2::XmpValue
XmpValue (TypeId typeId)
XmpArrayType xmpArrayType () const
Return XMP array type, indicates if an XMP value is an array.
XmpStruct xmpStruct () const
Return XMP struct, indicates if an XMP value is a structure.
size_t size () const override
Return the size of the value in bytes.
size_t copy (byte *buf, ByteOrder byteOrder=invalidByteOrder) const override
Write value to a character data buffer.
void setXmpArrayType (XmpArrayType xmpArrayType)
Set the XMP array type to indicate that an XMP value is an array.
void setXmpStruct (XmpStruct xmpStruct=xsStruct)
Set the XMP struct type to indicate that an XMP value is a structure.
int read (const byte *buf, size_t len, ByteOrder byteOrder=invalidByteOrder) override
Public Member Functions inherited from Exiv2::Value
Value (TypeId typeId)
Constructor, taking a type id to initialize the base class with.
Value (const Value &)=default
virtual ~Value ()=default
Virtual destructor.
virtual int setDataArea (const byte *buf, size_t len)
Set the data area, if the value has one by copying (cloning) the buffer pointed to by buf.
TypeId typeId () const
Return the type identifier (Exif data format type).
UniquePtr clone () const
Return an auto-pointer to a copy of itself (deep copy). The caller owns this copy and the auto-pointer ensures that it will be deleted.
std::string toString () const
Return the value as a string. Implemented in terms of write(std::ostream& os) const of the concrete class.
virtual size_t sizeDataArea () const
Return the size of the data area, 0 if there is none.
virtual DataBuf dataArea () const
Return a copy of the data area if the value has one. The caller owns this copy and DataBuf ensures that it will be deleted.
bool ok () const
Check the ok status indicator. After a to<Type> conversion, this indicator shows whether the conversion was successful.
Accessors
UniquePtr clone () const
size_t count () const override
Return the number of components of the value.
std::string toString (size_t n) const override
Return the n-th component of the value as a string. The behaviour of this method may be undefined if there is no n-th component.
int64_t toInt64 (size_t n=0) const override
Convert the n-th component of the value to an int64_t. The behaviour of this method may be undefined if there is no n-th component.
uint32_t toUint32 (size_t n=0) const override
Convert the n-th component of the value to a float. The behaviour of this method may be undefined if there is no n-th component.
float toFloat (size_t n=0) const override
Convert the n-th component of the value to a float. The behaviour of this method may be undefined if there is no n-th component.
Rational toRational (size_t n=0) const override
Convert the n-th component of the value to a Rational. The behaviour of this method may be undefined if there is no n-th component.
std::ostream & write (std::ostream &os) const override
Write all elements of the value to os, separated by commas.
Additional Inherited Members
Static Public Member Functions inherited from Exiv2::XmpValue
static XmpArrayType xmpArrayType (TypeId typeId)
Return XMP array type for an array Value TypeId, xaNone if typeId is not an XMP array value type.
Static Public Member Functions inherited from Exiv2::Value
static UniquePtr create (TypeId typeId)
A (simple) factory to create a Value type.
Protected Member Functions inherited from Exiv2::Value
Value & operator= (const Value &)=default
Assignment operator. Protected so that it can only be used by subclasses but not directly.
Protected Attributes inherited from Exiv2::Value
bool ok_ {true}
Indicates the status of the previous to<Type> conversion.
Detailed Description
Value type for simple arrays. Each item in the array is a simple value, without qualifiers. The array may be an ordered (seq), unordered (bag) or alternative array (alt). The array items must not contain qualifiers. For language alternatives use LangAltValue.
Uses a vector of std::string to store the value(s).
Member Function Documentation
read() [1/2]
int Exiv2::XmpValue::read override
Note
Uses read(const std::string& buf)
read() [2/2]
int Exiv2::XmpArrayValue::read (const std::string & buf) override virtual
Read a simple property value from buf and append it to the value.
Appends buf to the value after the last existing array element. Subsequent calls will therefore populate multiple array elements in the order they are read.
Returns
0 if successful.
Implements Exiv2::XmpValue.
toFloat()
float Exiv2::XmpArrayValue::toFloat (size_t n = 0) const override virtual
Convert the n-th component of the value to a float. The behaviour of this method may be undefined if there is no n-th component.
Returns
The converted value.
Implements Exiv2::Value.
References Exiv2::Value::ok_, and Exiv2::parseFloat().
toInt64()
int64_t Exiv2::XmpArrayValue::toInt64 (size_t n = 0) const override virtual
Convert the n-th component of the value to an int64_t. The behaviour of this method may be undefined if there is no n-th component.
Returns
The converted value.
Implements Exiv2::Value.
References Exiv2::Value::ok_, and Exiv2::parseInt64().
toRational()
Rational Exiv2::XmpArrayValue::toRational (size_t n = 0) const override virtual
Convert the n-th component of the value to a Rational. The behaviour of this method may be undefined if there is no n-th component.
Returns
The converted value.
Implements Exiv2::Value.
References Exiv2::Value::ok_, and Exiv2::parseRational().
toUint32()
uint32_t Exiv2::XmpArrayValue::toUint32 (size_t n = 0) const override virtual
Convert the n-th component of the value to a float. The behaviour of this method may be undefined if there is no n-th component.
Returns
The converted value.
Implements Exiv2::Value.
References Exiv2::Value::ok_, and Exiv2::parseUint32().
write()
std::ostream & Exiv2::XmpArrayValue::write (std::ostream & os) const override virtual
Write all elements of the value to os, separated by commas.
Note
The output of this method cannot directly be used as the parameter for read().
Implements Exiv2::Value.
The documentation for this class was generated from the following files:
value.hpp
value.cpp