export TOP_ROOT=$(shell realpath ../)/

all clean clobber:
	@$(MAKE) --directory=Stroika --no-print-directory $@
	@$(MAKE) --directory=expat --no-print-directory $@
	@$(MAKE) --directory=Exiv2 --no-print-directory $@
